name: ci

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.5

      - uses: actions/setup-node@v2.4.1
        with:
          node-version: 16
          cache: 'npm'

      - run: npm install

      - run: npm run lint

      - run: npm run test

      - uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.github_token }}

      - run: npm --no-git-tag-version version 1.0.$GITHUB_RUN_NUMBER

      - run: |
          echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}' > .npmrc
          npm publish
        if: github.ref == 'refs/heads/master'
        env:
          NPM_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
