name: ci

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.4

      - uses: actions/setup-node@v2.1.5
        with:
          node-version: 14

      - id: cache-node-modules
        uses: actions/cache@v2.1.5
        with:
          path: node_modules
          key: npm-${{ hashFiles('package-lock.json') }}

      - run: echo ${{steps.cache-node-modules.outputs.cache-hit}} ${{ steps.cache-node-modules.outputs.cache-hit == 'false'}}

      - if: ${{ steps.cache-node-modules.outputs.cache-hit != 'true' }}
        run: npm install

      - run: npm run lint

      - run: npm run test

      - uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.github_token }}

      - run: npm --no-git-tag-version version 1.0.$GITHUB_RUN_NUMBER

      - run: |
          echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}' > .npmrc
          npm publish
        if: github.ref == 'refs/heads/master'
        env:
          NPM_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
